version: '3'
services:
  db:
    image: postgres:latest
    container_name: postgres
    ports:
      - 5432:5432 
    volumes:
      - ./pg_data:/var/lib/postgresql/data/pgdata
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment: 
      POSTGRES_PASSWORD: root
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      PGDATA: /var/lib/postgresql/data/pgdata
    restart: always
  app:
    image: spicyfalafel/testbootvue:firsttry
    container_name: application
    ports: 
      - 9000:9000
    environment: 
      POSTGRES_HOST: db
    restart: always
    depends_on: 
      - db
  nginx:
    image: nginx:1.17.2-alpine
    container_name: nginx
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
    depends_on: 
      - app
      
